on:
  push:
    branches:
      - '*'
      - '**'

env:
  AWS_REGION: "eu-west-1"

jobs:
  # Builds a new container image, and pushes it on every commit to the repository
  # Also pushes a tag called "latest" to track the latest commit
  build_docker_image:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build container image
        run: docker build -t ppe .

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build -t ppe .
          docker tag ppe 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2026:$rev
          docker tag ppe 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2026:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2026:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2026:latest