on:
  push:
    branches:
      - '*'
      - '**'

defaults:
  run:
    working-directory: ./kjell

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build SAM application
        run: sam build --use-container

      # Deploy only on main branch
      - name: Deploy SAM application
        if: github.ref == 'refs/heads/main'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam2026stack --capabilities CAPABILITY_IAM
